# Generated by Django 5.1.2 on 2024-10-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок блога', max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Введите текст блога', verbose_name='Содержание')),
                ('publish_at', models.DateField(blank=True, help_text='Введите дату публикации', null=True, verbose_name='Дата публикации')),
                ('count_view', models.IntegerField(default=0, help_text='Счетчик просмотров', verbose_name='Количество просмотров')),
                ('photo', models.ImageField(blank=True, help_text='Загрузите фотографию блога', null=True, upload_to='blogs/photo', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
